version: "3.3"
services:
  init-account:
    image: ethereum/client-go:v1.13.11
    volumes:
      - ./config/init-new-account.sh:/root/init-new-account.sh
      - ./neutral/ethereum:/root/.ethereum
    entrypoint: "/root/init-new-account.sh"

  init-network:
    image: ethereum/client-go:v1.13.11
    volumes:
      - ./lib/jq:/usr/local/bin/jq
      - ./config/init-network.sh:/root/init-network.sh
      - ./neutral/ethereum:/root/.ethereum
    environment:
      - NETWORK_CHAIN_ID=5555
      - NETWORK_CLIQUE_PERIOD=15
      - NETWORK_CLIQUE_EPOCH=30000
      - NETWORK_ALLOC_BALANCE=0x200000000000000000000000000000000000000000000000000000000000000
    depends_on:
      - init-account
    entrypoint: "/root/init-network.sh"

  neutral:
    platform: linux/amd64
    build: ./neutral
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 30403:30303
      - 8645:8545
      - 8646:8546
    volumes:
      - ./neutral/ethereum:/root/.ethereum
    environment:
      - MY_IP=13.209.79.57
      - NETWORK_CHAIN_ID=5555
      - CHAIN_PORT=8545
      - CHAIN_WS_PORT=8546
      - CHAIN_NODE_PORT=30303
      - CHAIN_ALLOW_API=personal,miner,eth,net,txpool,debug,clique
      - CHAIN_NET_STATS_URL=neutral:NEUTRAL@neutral-netstats:3000
    networks:
      - neutral-network
    depends_on:
      - init-account
      - init-network

  neutral-netstats:
    image: kamael/eth-netstats
    ports:
      - '4500:3000'
    environment:
      - WS_SECRET=NEUTRAL
    networks:
      - neutral-network
    depends_on:
      - neutral

networks:
  neutral-network:
    driver: bridge